apiVersion: v1
kind: Service
metadata:
  name: wallet
  namespace: wallet
  labels:
    app: wallet
spec:
  type: NodePort
  selector:
    app: wallet-svc
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080