apiVersion: v1
kind: Service
metadata:
  name: wallet
  namespace: wallet
  labels:
    app: wallet
spec:
  type: ClusterIP
  selector:
    app: wallet
  ports:
    - name: http
      port: 8080
      targetPort: 8080
